// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCk2sqHaeY1z9t9Eoa6QLOTUbQ09MJefY',
    appId: '1:193749127321:web:39e2bd5696924546d7e808',
    messagingSenderId: '193749127321',
    projectId: 'gettogether-bbe79',
    authDomain: 'gettogether-bbe79.firebaseapp.com',
    storageBucket: 'gettogether-bbe79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDE3LvAZ9R5hpcLUCoZOgD0_FJB6dQDL4',
    appId: '1:193749127321:android:37a3cb39978db952d7e808',
    messagingSenderId: '193749127321',
    projectId: 'gettogether-bbe79',
    storageBucket: 'gettogether-bbe79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPVQXApoK-cTsiMOoa1ToRI23ZcV5tgfI',
    appId: '1:193749127321:ios:d565c41f6835770bd7e808',
    messagingSenderId: '193749127321',
    projectId: 'gettogether-bbe79',
    storageBucket: 'gettogether-bbe79.appspot.com',
    iosBundleId: 'com.example.grtTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPVQXApoK-cTsiMOoa1ToRI23ZcV5tgfI',
    appId: '1:193749127321:ios:1829f3b00e2100cbd7e808',
    messagingSenderId: '193749127321',
    projectId: 'gettogether-bbe79',
    storageBucket: 'gettogether-bbe79.appspot.com',
    iosBundleId: 'com.example.grtTogether.RunnerTests',
  );
}
